spring.application.name=tradeformservice
logging.file.name=logs/${spring.application.name}.log
logging.file.path=logs
#spring.datasource.url=jdbc:mysql://localhost:3306/tradeformdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# driv
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/tradeformdb
